## Numerical Python End to End in Details


### Numpy

#### Numpy is a Numerical python 

It is developed Travis oliphant in 2005

Numpy  has function to work on linear algebra, fourier trasform, and matrices 

its basicaallly used to work with array,it can work with multidimentional array

# Why


Numpy is built using python , and most of the which requires faster excution is developed 
using C or C++,so it is very fast in excution

Numpy arrays are called as ndarray

Numpy has 50X speed  as compared too python list

Numpy provides lots of functions which can be performed on large date

Numpy gives faster response as compared to list as it stores numpy arrays at one continous location

### Installation of Numpy

Go to terminal and use below command, without!

! pip install numpy

you can use other tools like  spyder or annaconda wnich comes
with its installation

In [2]:
#create a numpy array using list

import numpy as np

print("numpy version is :",np.__version__)

list1 = [1,2,3,4,5,6,7]
print(list1)
print(type(list))
x = np.array(list1)
print(x)
print(type(x))

numpy version is : 1.24.2
[1, 2, 3, 4, 5, 6, 7]
<class 'type'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [3]:
# How to access the element 
# its 1- D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# lets check the dimention of the array
print(x.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [6]:
# creat a numpy  array using list

arr = np.array ([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

print('*'*60)

lst = [10,20,30,40]
ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
************************************************************
[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
# how to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
# lets check the dimentions of the array
print('Number of dimention:',arr.ndim)

[1 2 3 4 5 6 7 8 9]
Number of dimention: 1


In [9]:
# craete numpy array using tuple

tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# different dimentional arrays:

In [10]:
# 1. 0-D array

arr = np.array (9)
print(arr)
print(type(arr))
print("Dimention of array :",arr.ndim)

9
<class 'numpy.ndarray'>
Dimention of array : 0


In [12]:
# 2. 1-D array 

arr= np. array([1,2,3,4,45])
print(arr)
print(type(arr))
print("Dimensons of array:", arr.ndim)

# access element an 1-D Array 
print ('element present at 4th index:', arr[4])

[ 1  2  3  4 45]
<class 'numpy.ndarray'>
Dimensons of array: 1
element present at 4th index: 45


In [13]:
# 3 2-D array 
# Arrray having 1- D array as input eleement ara called as  2-D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print("Dimention of array:",arr.ndim)

# Acess eleemn an 2-D  array
# Array having 1-D array as input element are called as 2-D array


print('Element present at lst in axis 0:',arr[0,1]) # array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimention of array: 2
Element present at lst in axis 0: 2


In [14]:
import numpy as np
ar = [[1,2,3,4],[4,5,6,7],[4,5,6,7],[4,5,6,7]]
arr = np.array(ar)
print(arr)
print("Dimention:",arr.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimention: 2


In [22]:
#Access the element of 2-D array


print(arr)
#dimention
print("Dimention:",arr.ndim)
print('*'*60)

#one way is to write
print('arr[0][3]:',arr[0][3])
print('*'*60)

print('arr[0]:',arr[0])
print('*'*60)

print('arr[0][2]:',arr[0][2])
print('*'*60)

#anather way is like
print('arr[1]:',arr[1])
print('arr[3,1]:',arr[3,1])

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimention: 2
************************************************************
arr[0][3]: 4
************************************************************
arr[0]: [1 2 3 4]
************************************************************
arr[0][2]: 3
************************************************************
arr[1]: [4 5 6 7]
arr[3,1]: 5


In [25]:
#4].  3-D array
# array  that has 2-D array (matrices)as its element is called 

ar= [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]
print(ar)
print(type(ar))

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
