## Numerical Python End to End in Details


### Numpy

#### Numpy is a Numerical python 

It is developed Travis oliphant in 2005

Numpy  has function to work on linear algebra, fourier trasform, and matrices 

its basicaallly used to work with array,it can work with multidimentional array

# Why


Numpy is built using python , and most of the which requires faster excution is developed 
using C or C++,so it is very fast in excution

Numpy arrays are called as ndarray

Numpy has 50X speed  as compared too python list

Numpy provides lots of functions which can be performed on large date

Numpy gives faster response as compared to list as it stores numpy arrays at one continous location

### Installation of Numpy

Go to terminal and use below command, without!

! pip install numpy

you can use other tools like  spyder or annaconda wnich comes
with its installation

In [1]:
#create a numpy array using list

import numpy as np

print("numpy version is :",np.__version__)

list1 = [1,2,3,4,5,6,7]
print(list1)
print(type(list))
x = np.array(list1)
print(x)
print(type(x))

numpy version is : 1.24.2
[1, 2, 3, 4, 5, 6, 7]
<class 'type'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
# How to access the element 
# its 1- D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# lets check the dimention of the array
print(x.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [3]:
# creat a numpy  array using list

arr = np.array ([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

print('*'*60)

lst = [10,20,30,40]
ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
************************************************************
[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
# how to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
# lets check the dimentions of the array
print('Number of dimention:',arr.ndim)

[1 2 3 4 5 6 7 8 9]
Number of dimention: 1


In [5]:
# craete numpy array using tuple

tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
# different dimentional arrays:

In [7]:
# 1. 0-D array

arr = np.array (9)
print(arr)
print(type(arr))
print("Dimention of array :",arr.ndim)

9
<class 'numpy.ndarray'>
Dimention of array : 0


In [8]:
# 2. 1-D array 

arr= np. array([1,2,3,4,45])
print(arr)
print(type(arr))
print("Dimensons of array:", arr.ndim)

# access element an 1-D Array 
print ('element present at 4th index:', arr[4])

[ 1  2  3  4 45]
<class 'numpy.ndarray'>
Dimensons of array: 1
element present at 4th index: 45


In [9]:
# 3 2-D array 
# Arrray having 1- D array as input eleement ara called as  2-D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print("Dimention of array:",arr.ndim)

# Acess eleemn an 2-D  array
# Array having 1-D array as input element are called as 2-D array


print('Element present at lst in axis 0:',arr[0,1]) # array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimention of array: 2
Element present at lst in axis 0: 2


In [10]:
import numpy as np
ar = [[1,2,3,4],[4,5,6,7],[4,5,6,7],[4,5,6,7]]
arr = np.array(ar)
print(arr)
print("Dimention:",arr.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimention: 2


In [11]:
#Access the element of 2-D array


print(arr)
#dimention
print("Dimention:",arr.ndim)
print('*'*60)

#one way is to write
print('arr[0][3]:',arr[0][3])
print('*'*60)

print('arr[0]:',arr[0])
print('*'*60)

print('arr[0][2]:',arr[0][2])
print('*'*60)

#anather way is like
print('arr[1]:',arr[1])
print('arr[3,1]:',arr[3,1])

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimention: 2
************************************************************
arr[0][3]: 4
************************************************************
arr[0]: [1 2 3 4]
************************************************************
arr[0][2]: 3
************************************************************
arr[1]: [4 5 6 7]
arr[3,1]: 5


In [12]:
#4].  3-D array
# array  that has 2-D array (matrices)as its element is called 

ar= [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]
print(ar)
print(type(ar))
print('*'*60)

arr=np.array(ar)
print(arr)
print(type(arr))
print('*'*100)

print('Dimention of array:', arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
************************************************************
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
Dimention of array: 3


In [13]:
# access the element of the 3-D array 

print(arr)
print(type(arr))
print('*'*100)

print('One way is :')
print('arr[1]:',arr[1])
print('arr[0][0]:',arr[0][0])
print('arr[0][0][2]:',arr[0][0][2])

print('*'*100)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
One way is :
arr[1]: [[10 20 30]
 [40 50 60]]
arr[0][0]: [1 2 3]
arr[0][0][2]: 3
****************************************************************************************************


## Creat an n dimention array

 lower dimention to lower dimention will possible by using  ndmin funtion for we need to go with array.reshape(funtion)
 
 
 ndim = ..1./2/3/4/5/...
 
 but higher dimention to lower dimention will possible by using ndim function for we need to go with array.reshape() function

In [14]:
# creat an n dimention array 
arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print('Number of dimention:',arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimention: 5


In [15]:
# lower to higher is possible but higher to lower not possible
import numpy as np
arr1 = np.array([[[[[1,2,3]]]]],ndmin=3)
arr1,arr1.ndim

(array([[[[[1, 2, 3]]]]]), 5)

In [16]:
arr2 = np.array([1,2,3],ndmin=3)
arr2,arr2.ndim

(array([[[1, 2, 3]]]), 3)

In [17]:
arr11 = np.array([1,2,3,4])
arr10 = arr11.reshape((1,1,1,1,4))
arr10.ndim

5

In [18]:
b = np.array([[[1,2,3],[4,5,6,]],[[10,20,30],[40,50,60]]])
print(b,b.ndim)
b.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]] 3


(2, 2, 3)

In [19]:
b=np.array ([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
b,b.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[10, 20, 30],
         [40, 50, 60]]]),
 3)

In [20]:
b[0,1,2]

6

## Array Slicing

In [21]:
arr = np.array([1,2,3,4],ndmin=5)
arr,arr.ndim,arr.shape



(array([[[[[1, 2, 3, 4]]]]]), 5, (1, 1, 1, 1, 4))

In [22]:
# 5d array slicing

print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])


1
2
3
4


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# slice
print("Length:",len(arr))
print(arr[5:9])
print(arr)

# [start:end], start include ,end excluded

[1 2 3 4 5 6 7 8 9]
Length: 9
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [24]:
print(arr)
print(arr[0:5])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


## Negative indices

####  Negative indices always start from last element of n-d 
#### array i.e -1st index is last element of ndarray

In [25]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [26]:
print(arr[-1])
print(arr[-5])
print(arr[-9])

9
5
1


In [27]:
# step value in slincing a numpy array
# here step is 2 
print(arr)
print(arr[0:9:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [28]:
print(arr[::2]) # ::2 >> 0 to 9 index by step index 2
print(arr[0:6:2]) # 0:6:2 >> 0 to 6 index by step value 2


[1 3 5 7 9]
[1 3 5]


### Slincing of 2D Array

In [29]:
arr = np .array([[1,2,3,4,5],[6,7,8,9,10]])

print (arr)
print('\n')
print(arr[1,2])
print(arr[1,1:4]) # arr
print(arr[0,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8
[7 8 9]
[2 3 4]


In [30]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
arr[0:,2:3]

array([[3],
       [8]])

In [32]:
arr[0:,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [33]:
arr[0,:3]

array([1, 2, 3])

In [34]:
print(arr[0:1,0:3])  # arr[location index from to,element index]


[[1 2 3]]


In [35]:
print(arr[0:2,2])

[3 8]


In [36]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size,arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15 (3, 5)


In [37]:
# 2, 3 
# 20,30
print(arr[0:2,1:3])

print('\n')

# 20,30,40
# 22,33,44

print(arr[1:,1:4])

[[ 2  3]
 [20 30]]


[[20 30 40]
 [22 33 44]]


## Slicing of 3D array

In [38]:
arr   = np.array([[[1,2,3],[5,6,7]],[[11,22,33],[55,66,77]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]
3


In [39]:
arr[0][1][1:3] # [array location, array row location, array ]

array([6, 7])

In [40]:
arr[1,1,0:2]

array([55, 66])

In [41]:
arr[1][1][1:3]

array([66, 77])

# Data types in Numpy

# list of all data types in numpy

In [42]:
i/Int -integer
Bool - boilean 
unit - unsigned intger 
f/Float - Complex Float
string - string
m - datatime
m - timedelta
o - object 
U - unicode string

SyntaxError: invalid syntax (1226495924.py, line 3)

In [ ]:
import numpy as np


In [ ]:
# dype 

arr = np.array ([1,2,3,4])
print(arr.dtype)

In [ ]:
arr = np. array(['apple','banana','cherry'])
print(arr.dtype)

In [ ]:
# creating arrays with a defined data type

arr = np.array([1,2,3,4],dtype=str)
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4],dtype='i')  #int
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4,5,6],dtype='f')
print(arr)
print(arr.dtype)

In [ ]:
arr= np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(arr.dtype)

In [ ]:
# int with 4 byts

arr = np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

print('*'*100)

arr = np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

In [ ]:
# in python we are not responsible for memory management PVM is responsible for memory management

In [ ]:
arr = np .array(['1','2','3'],dtype='i')
print(arr)

## Data Type Conversion

In [ ]:
# float to int

arr = np.array([1.1,2.2,3.3,4.4])
print('old array :',arr)
print('old array data type :', arr.dtype)
print('*'*100)
new_arr = arr.astype('i')
print('new array',new_arr)
print('new array data type :',new_arr.dtype)


In [ ]:
# int to bool 
arr = np.array([1,2,3,4,0])
print('old array:',arr)
print('old array data type:',arr.dtype)
print('*'*100)
new_arr = arr.astype (bool)
print('new array',new_arr)
print('new array data type:',new_arr.dtype)

## Differance between copy and view

## Copy :
#### A copy is a new array that has the same data as the original array.changes made to the copy do not affect the original array, and vice versa


## View :
#### A view is a new array that refers to the same data as the orinal array. changes made to the view affect the original array , and vice versa


In [ ]:
a = np.array([1,2,3,4,5])
print('original array:',a)
b=a.copy()
print('copid array:',b)
print('now we will update the original array "1 to 100"')
a[0]=100
print('original array after update :',a)
print('copied array after update in original:',b)

In [ ]:
a=np.array([1,2,3,4,5])
print('original array:',a)
b=a .view()
print('copied array :',a)
print('now we will update the original array "1 to 100"')
a[0]=100

print('original array after update :',a)
print('copied array after update in original :',b)


In [ ]:
# copy : it is going to creat new instance fpr ypur value

arr = np .array([1,2,3,4,5])
x = arr.copy()# separat object required 
arr[0]= 42 # updated arr 0 th index

print (arr )
print(x)

In [ ]:
arr = np.array ([1,2,3,4,5,6])
x = arr.copy()# separat object required
print(x)
x[0] = 100
print(x)

print(arr)
#print(x)

In [ ]:
# view 

arr = np.array([1,2,3,4,5])
x = arr.view ()

#x = arr 
x[0] = 200
print(x)
print(x)

In [ ]:
a = np.array ([1,2,3])
b = a.view()
b[0]=4


print(a)# output : [4,2,3]
print(b)# output: [4,2,3]

### Base concept : how to identify copy or  view

#### That will possible  by using "base" fuction
if you are referring to identifying whether a numpy array is a copy or a view (a differant view of the same data) , you can use the base attribute of the array.the base attribute returns none for arrays that own their data and it returns the base object forrrrrrr arrays that are views

In [ ]:
arr = np .array([1,2,3,4,5])

x = arr.copy()
y = arr .view()

print(x.base )
print(y.base)

## Numpy Array Reshaping 

In [ ]:
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.shape)
print(arr.shape)
print('\n')
newarr=arr.reshape(12,1)
print(newarr)
                

In [ ]:
print(arr)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.size)
print(arr.shape)
print('\n')
newarr=arr.reshape(3,2,2)
print(newarr)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3)
print(newarr)

In [ ]:
# creat a 2D array and then covert it into 1D array

arr = np.array([[11,44,77,88,99,55]])
newarr=arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

In [ ]:
arr = np.array([[11,44,77],[88,99,55]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

In [ ]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape(3,2)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

In [ ]:
# cvert 3D array into 1D array
arr = np.array([[[11,44,77,88,99,55]],[[111,441,717,188,919,515]]])
newarr = arr.reshape(12,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

In [ ]:
arr = np.array([11,44,77,88,99,55,111,441,717,188,919,515])
newarr = arr.reshape(1,3,4)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

In [ ]:
import numpy as np


In [ ]:
# convert 4D array into 1D array 
arr = np.array ([[[[11,44,77,88,99,55]]]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)


In [ ]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape((3,2))
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

## Numpy Array Reshape Flatten Unknown Dimention

#### if user dont know any one dimention out 3 dimention then numpy can obtain it for user have mention the _1 for thaat dim

In [ ]:
# unkown Dimention 
arr = np.array ([1,2,3,4,5,6,7,8,9])

newarr = arr.reshape(3,3,-1)
print(newarr)

#### if u want to a 1-D  Araay using N-D array 

In [ ]:
# flattenting (reshshape/covrt in scalar vector) an array

arr = np.array([[10,20,30],[40,50,60]])

print(arr)
print(arr.shape)

newarr=arr.reshape(-1)
print(newarr)

## Numpy Array Iterating

### iterating means that you going each element of the array

In [ ]:
# iterating on 2-D array 
arr = np.array ([[11,22,33],[10,20,30]])

# print(arr)

for x in arr: # x is taking elements here
    print(x)

In [ ]:
# interating on scalarelement of 2-D array

arr = np.array([[1,2,3],[4,5,6]])
for x in arr : # here x is hplding list of element
    for i in x:
        print(i)
    

In [ ]:
#iterating on scalar elememntof 3-D array

arr = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr : 
#    print(x,'\n')
    for i in x:
        for j in i :
            print(j,'\n')

### using nditer()

In [ ]:
# iterating on 3-D array 
arr =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
    
y = np .nditer(arr)

for x in y:
        print(x)

In [ ]:
arr = np.array([[1,2,3,4],[88,88,3939,999]])

print(np.nditer(arr))
for i in np.nditer(arr):
    print(i)

In [ ]:
for i in np.nditer(arr,flags = ['buffered'],op_dtypes=["complex"]):
    print(i)

In [ ]:
#  slicing of an numpy array in interations 
# 2d  array 

arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[0:,0:3:2]):# [array location , index number]
    print(x)

In [ ]:
# 3d array
# array [start:end:step , start:end:step, start:end :step]

arr = np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])
for i in np.nditer(arr[1:,1:,1:2]):
    print(i)

In [ ]:
array_3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

# slice the array along the sirst dimention 
for i in np.nditer(array_3d[:,:,:]):
    print(i)

In [ ]:
array_3d = np .array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

# slice the array with a step size of 2 along thee first dimention
for i in np.nditer(array_3d[:,::,::2]):
    print(i)

### 2.using ndenumerate()

enumeration means mentioing sequence number of something one by one 

Whenever we want to acess any location of element in multi dimentional arrays that time we can use ""ndenumerate"

this method always return tuple of index and element

In [ ]:
arr = np.array([1,2,3])

for x in np.ndenumerate(arr):
    print(x)
    
print('*'*100)

for i,x in np.ndenumerate(arr):
    print("index :, ",i,"value",x)

In [ ]:
# 2D array
arr = np.array ([[1,2,3,4],[5,6,7,8]])

print(arr)

for i,val in np.ndenumerate(arr):
    print("Index :",i,"value",val)

## joining Array


##### while joining array we should remember "both arrays should have same dimention"

#### using concatenation

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)

In [ ]:
# array concatenate using axis option 

#axis =0 : it represents rows (defaults)
# axis = 1 : it represent colomns

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])


arr = np.concatenate ((arr1,arr2),axis=0)# columnwise
print(arr)

print("*"*100)


arr = np.concatenate((arr1,arr2),axis=0)# rowwise
print(arr)

### 2.using stack fuction 

stackin is same as concatenating , the only differance is that stacking is done along a new axis

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr  = np.stack((arr1,arr2),axis=1)
print(arr)

print('*'*100)

arr=np.stack((arr1,arr2),axis=0)
print(arr)

#### 2.1 using "vstack function("

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr = np.vstack((arr1,arr2))

print(arr)

#### 2.3 using "dstack fuction()"

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2))

print(arr)

In [ ]:
arr1 = np.array([[1,2,3],[11,22,33]])

arr2 = np.array([[4,5,6],[44,55,66]])

arr = np.dstack((arr1,arr2))

# it stand for "depth wise stack" and is used stack arrays

print(arr)

### Spliting Array

##### joining meres multiple arrays into ne and spltting
breaks one array into multiple 

syntax:
    
np.arrays_split(array,no_split)
np.split (array,no.split)

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)

newarr = np.split(arr,3)
print(newarr)

print('*'*100)

for i in newarr:
    print (i)

In [ ]:
# using axis 

arr = np.array([[1,2,3],
               [4,5,6]])
print(arr)
newarr=np.split(arr,3,axis=1)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

In [ ]:
# using axis 

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

newarr=np.split(arr,2,axis=0)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)
newarr = np.split (arr,3)
# newarr = np.split (arr,4)# this will raise an value error
print(newarr)

for i in newarr:
    print(i)

2. array_split()

if no of ele,ment are less tan it adjust in last array

it dones raise error this will adjust the element in array

In [ ]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,2)
print(newarr)

In [ ]:
newarr= np.array_split(arr,3)
print(newarr)

In [ ]:
newarr = np.array_split(arr,5)
print(newarr)

print('*'*100)

print(newarr[1])

In [ ]:
# splitg on 2-D array 

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

In [ ]:
arr=np.array([[1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12]])
       
newarr =np.array_split(arr,2,axis=1)
print(newarr)
       

In [ ]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

newarr=np.array_split(arr,4,axis=0)

for i in newarr:
    print(i,'\n')

In [ ]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,2,axis=1)

for i in newarr:
    print(i,'\n')

In [ ]:
# Array splitting on axis
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])

# print(arr)

newarr = np.array_split(arr, 3, axis=1)

print(newarr) 

print('*'*100)
print(arr,'\n')
newarr = np.array_split(arr, 3, axis=0)

print(newarr)

#### 3. Using hsplit()opposite of h stack()

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],
                [13,14,15],[16,17,18]])

print(arr,'\n')
print('hstack(methos:\n')
newarr = np.hstack(arr)
print(newarr,'\n')
newarr = np.hsplit(arr, 3)
# print(arr.shape)
print('hsplit() method:\n')
print(newarr)

###  Searching Arrays

### The "where" method is used for searching the array

#### 1. Where 

In [ ]:
# finding element in 1-D array
import numpy as np
arr = np .array([1,2,3,4,5,4,5])
x=np.where(arr==4)#element

print(arr)
print("Location of index:",x)

In [ ]:
# Arthmatic opration an numpy array

arr = np .array([[1,2,3],[4,5,6]])
print(arr)

print('\nAddition:',arr+1) # one element added in every element 
print('\nsubtractoion:',arr-1)
print('\nmultiplication:',arr*2)
print('\nDivision:',arr/2)


In [ ]:
# find the location of even number in my numpy array
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2==0)

print(arr)
print("Even number array:",x)

In [ ]:
# find the location of odd number in numpy array 

arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
loc=np.where(arr%2==1)

print('odd number location:',loc)

### Searchshorted()

#### Perform a binary searchin the array and returens the index where the specified value would be inserted to martiain the search order 

##### this method does not insert elements , it just returns a location for element in the numpy array

In [ ]:
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr,7,side='left')# >>

print(arr)
print('location where element to be inserted',loc)


In [ ]:
arr=np.array([5,7,8,9])

loc = np.searchsorted(arr,7,side='right')
print('location where element to be inserted',loc)

In [ ]:
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr,8.5,side ='right')

print (arr)

print('location where element to be inserted',loc)


In [ ]:
# multiple values 

arr = np.array ([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print('location where elemet to be inserted',x)

### Sorting Arrays

### sorting means puting element in an ordered sequence like numric or alphabeticcal,ascending or descending 

### sort(), that will sort a specified array


In [ ]:
# sort () on numerical array 

arr = np.array([3,2,0,1])
res=np.sort(arr)
print("input array",arr)
print('Sorted Array',res)

In [ ]:
# sort () on string array

arr = np.sort (arr)

print('input array ',arr)
print('sorted array',res)

In [ ]:
# sort() on string array
arr = np.array(['banana', 'cherry', 'apple'])

res = np.sort(arr)

print('Input Array',arr)

print('Sorted Array',res)

In [ ]:
# sort ()on 2d array

arr = np.array([[3,2,4],[5,0,1]])
res=np.sort(arr)

print('input array:\n',arr)
print('sorted array:\n',res)

In [ ]:
# work an axis =0
arr=np.array([[3,2,4],[5,0,1]])
print(arr)


# axis (axis=0)
# which will result in a sorted 2d array where each column is 

print("sorting on 0 axis :\n",arr)
res=np.sort(arr,axis=0)
print("\n",res)

# axis (axis=1)
# which will in a sorted 2D array where each row is sort
print("Sorting on 1axis:\n",arr)
res=np.sort(arr,axis=1)
print("\n",res)

In [ ]:
import numpy as np

# Creat a 2d array
a = np.array([[3,2,4],
             [1,5,6],
             [9,7,8]])

# sort the rows of the array along axis 1
sorted_array = np.sort(a,axis=1)
print('\n',sorted_array)
#sort the column of the array alaong axis 0
sorted_array=np.sort(a,axis=0)
print('\n',sorted_array)

## Filter Array

#### 1.Getting some elements out of an exiting array and creating a new array out them is called filtering

#### 2. Numpy filter an array using boolean list 

#### 3. A boolean index list is a list booleans corresponding to indexes ain the array

In [ ]:
arr=np.array([1,2,3,4,5])
x=[True,False,True,False,True]

newarr =arr[x]
print(newarr)

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
# creat an empty list
index=[]

# go through element in arr
for element in arr:
    # if the element is higher than 4,set the value to true,
    if element>4:
        index.append(True)
    else:
        index.append(False)
        
print(index)
newarr=arr[index]
print(newarr)

In [ ]:
# print a last of even number from original list using array filter

print(arr)

index=[]
# i % 2 == 0

for i in arr:
    if i %2 ==0:
        index.append(True)
    else:
        index.append(False)
        
print(index)

newarr = arr[index]
print(newarr)

In [ ]:
arr = np.array([11,223,45,8787,655,44,33,333,2,3,3,10])

filter_arr=arr>100
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

### Other NumPy Functions


In [ ]:
arr = np.arange(10)
print(arr)

In [ ]:
arr=np.arange(5,25)
print(arr)

In [ ]:
arr=np.arange(5,51,5)
print(arr)

## Reshape

###### np.reshape(input,(shape))
###### array.reshape(shape)

In [ ]:
## 1D to 2D conversion
arr=np.arange(0,25)
print(arr)
# one way
arr_2d=np.reshape(arr,(5,5))# or arr.reshape(5,5)
print('\n',arr_2d)


In [ ]:
arr =np.arange(0,25)
print(arr)

In [ ]:
arr = np.arange(0,25)
print(arr)

# anather way
arr_2d=arr.reshape(1,5,5)
print('\n',arr_2d)


In [ ]:
arr_2d.min()

## 4.max()

#### The numpy.max()fuction is used to find the maximum value tin the arr array

In [ ]:
arr_2d.max()

### 5. argmax()


##### the numpy .argumax() function is used to find the index of the maximum 