## Numerical Python End to End in Details


### Numpy

#### Numpy is a Numerical python 

It is developed Travis oliphant in 2005

Numpy  has function to work on linear algebra, fourier trasform, and matrices 

its basicaallly used to work with array,it can work with multidimentional array

# Why


Numpy is built using python , and most of the which requires faster excution is developed 
using C or C++,so it is very fast in excution

Numpy arrays are called as ndarray

Numpy has 50X speed  as compared too python list

Numpy provides lots of functions which can be performed on large date

Numpy gives faster response as compared to list as it stores numpy arrays at one continous location

### Installation of Numpy

Go to terminal and use below command, without!

! pip install numpy

you can use other tools like  spyder or annaconda wnich comes
with its installation

In [1]:
#create a numpy array using list

import numpy as np

print("numpy version is :",np.__version__)

list1 = [1,2,3,4,5,6,7]
print(list1)
print(type(list))
x = np.array(list1)
print(x)
print(type(x))

numpy version is : 1.24.2
[1, 2, 3, 4, 5, 6, 7]
<class 'type'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
# How to access the element 
# its 1- D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# lets check the dimention of the array
print(x.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [3]:
# creat a numpy  array using list

arr = np.array ([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

print('*'*60)

lst = [10,20,30,40]
ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
************************************************************
[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
# how to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
# lets check the dimentions of the array
print('Number of dimention:',arr.ndim)

[1 2 3 4 5 6 7 8 9]
Number of dimention: 1


In [5]:
# craete numpy array using tuple

tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
# different dimentional arrays:

In [7]:
# 1. 0-D array

arr = np.array (9)
print(arr)
print(type(arr))
print("Dimention of array :",arr.ndim)

9
<class 'numpy.ndarray'>
Dimention of array : 0


In [8]:
# 2. 1-D array 

arr= np. array([1,2,3,4,45])
print(arr)
print(type(arr))
print("Dimensons of array:", arr.ndim)

# access element an 1-D Array 
print ('element present at 4th index:', arr[4])

[ 1  2  3  4 45]
<class 'numpy.ndarray'>
Dimensons of array: 1
element present at 4th index: 45


In [9]:
# 3 2-D array 
# Arrray having 1- D array as input eleement ara called as  2-D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print("Dimention of array:",arr.ndim)

# Acess eleemn an 2-D  array
# Array having 1-D array as input element are called as 2-D array


print('Element present at lst in axis 0:',arr[0,1]) # array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimention of array: 2
Element present at lst in axis 0: 2


In [10]:
import numpy as np
ar = [[1,2,3,4],[4,5,6,7],[4,5,6,7],[4,5,6,7]]
arr = np.array(ar)
print(arr)
print("Dimention:",arr.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimention: 2


In [11]:
#Access the element of 2-D array


print(arr)
#dimention
print("Dimention:",arr.ndim)
print('*'*60)

#one way is to write
print('arr[0][3]:',arr[0][3])
print('*'*60)

print('arr[0]:',arr[0])
print('*'*60)

print('arr[0][2]:',arr[0][2])
print('*'*60)

#anather way is like
print('arr[1]:',arr[1])
print('arr[3,1]:',arr[3,1])

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimention: 2
************************************************************
arr[0][3]: 4
************************************************************
arr[0]: [1 2 3 4]
************************************************************
arr[0][2]: 3
************************************************************
arr[1]: [4 5 6 7]
arr[3,1]: 5


In [12]:
#4].  3-D array
# array  that has 2-D array (matrices)as its element is called 

ar= [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]
print(ar)
print(type(ar))
print('*'*60)

arr=np.array(ar)
print(arr)
print(type(arr))
print('*'*100)

print('Dimention of array:', arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
************************************************************
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
Dimention of array: 3


In [13]:
# access the element of the 3-D array 

print(arr)
print(type(arr))
print('*'*100)

print('One way is :')
print('arr[1]:',arr[1])
print('arr[0][0]:',arr[0][0])
print('arr[0][0][2]:',arr[0][0][2])

print('*'*100)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
One way is :
arr[1]: [[10 20 30]
 [40 50 60]]
arr[0][0]: [1 2 3]
arr[0][0][2]: 3
****************************************************************************************************


## Creat an n dimention array

 lower dimention to lower dimention will possible by using  ndmin funtion for we need to go with array.reshape(funtion)
 
 
 ndim = ..1./2/3/4/5/...
 
 but higher dimention to lower dimention will possible by using ndim function for we need to go with array.reshape() function

In [14]:
# creat an n dimention array 
arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print('Number of dimention:',arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimention: 5


In [15]:
# lower to higher is possible but higher to lower not possible
import numpy as np
arr1 = np.array([[[[[1,2,3]]]]],ndmin=3)
arr1,arr1.ndim

(array([[[[[1, 2, 3]]]]]), 5)

In [16]:
arr2 = np.array([1,2,3],ndmin=3)
arr2,arr2.ndim

(array([[[1, 2, 3]]]), 3)

In [17]:
arr11 = np.array([1,2,3,4])
arr10 = arr11.reshape((1,1,1,1,4))
arr10.ndim

5

In [18]:
b = np.array([[[1,2,3],[4,5,6,]],[[10,20,30],[40,50,60]]])
print(b,b.ndim)
b.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]] 3


(2, 2, 3)

In [19]:
b=np.array ([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
b,b.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[10, 20, 30],
         [40, 50, 60]]]),
 3)

In [20]:
b[0,1,2]

6

## Array Slicing

In [21]:
arr = np.array([1,2,3,4],ndmin=5)
arr,arr.ndim,arr.shape



(array([[[[[1, 2, 3, 4]]]]]), 5, (1, 1, 1, 1, 4))

In [22]:
# 5d array slicing

print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])


1
2
3
4


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# slice
print("Length:",len(arr))
print(arr[5:9])
print(arr)

# [start:end], start include ,end excluded

[1 2 3 4 5 6 7 8 9]
Length: 9
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [24]:
print(arr)
print(arr[0:5])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


## Negative indices

####  Negative indices always start from last element of n-d 
#### array i.e -1st index is last element of ndarray

In [25]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [26]:
print(arr[-1])
print(arr[-5])
print(arr[-9])

9
5
1


In [27]:
# step value in slincing a numpy array
# here step is 2 
print(arr)
print(arr[0:9:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [28]:
print(arr[::2]) # ::2 >> 0 to 9 index by step index 2
print(arr[0:6:2]) # 0:6:2 >> 0 to 6 index by step value 2


[1 3 5 7 9]
[1 3 5]


### Slincing of 2D Array

In [29]:
arr = np .array([[1,2,3,4,5],[6,7,8,9,10]])

print (arr)
print('\n')
print(arr[1,2])
print(arr[1,1:4]) # arr
print(arr[0,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8
[7 8 9]
[2 3 4]


In [30]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
arr[0:,2:3]

array([[3],
       [8]])

In [32]:
arr[0:,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [33]:
arr[0,:3]

array([1, 2, 3])

In [34]:
print(arr[0:1,0:3])  # arr[location index from to,element index]


[[1 2 3]]


In [35]:
print(arr[0:2,2])

[3 8]


In [36]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size,arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15 (3, 5)


In [37]:
# 2, 3 
# 20,30
print(arr[0:2,1:3])

print('\n')

# 20,30,40
# 22,33,44

print(arr[1:,1:4])

[[ 2  3]
 [20 30]]


[[20 30 40]
 [22 33 44]]


## Slicing of 3D array

In [38]:
arr   = np.array([[[1,2,3],[5,6,7]],[[11,22,33],[55,66,77]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]
3


In [39]:
arr[0][1][1:3] # [array location, array row location, array ]

array([6, 7])

In [40]:
arr[1,1,0:2]

array([55, 66])

In [41]:
arr[1][1][1:3]

array([66, 77])

# Data types in Numpy

# list of all data types in numpy

In [42]:
i/Int -integer
Bool - boilean 
unit - unsigned intger 
f/Float - Complex Float
string - string
m - datatime
m - timedelta
o - object 
U - unicode string

SyntaxError: invalid syntax (1226495924.py, line 3)

In [43]:
import numpy as np


In [44]:
# dype 

arr = np.array ([1,2,3,4])
print(arr.dtype)

int32


In [45]:
arr = np. array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [46]:
# creating arrays with a defined data type

arr = np.array([1,2,3,4],dtype=str)
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [47]:
arr = np.array([1,2,3,4],dtype='i')  #int
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [48]:
arr = np.array([1,2,3,4,5,6],dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [49]:
arr= np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float64


In [50]:
# int with 4 byts

arr = np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

print('*'*100)

arr = np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
****************************************************************************************************
[1 2 3 4]
int32


In [51]:
# in python we are not responsible for memory management PVM is responsible for memory management

In [52]:
arr = np .array(['1','2','3'],dtype='i')
print(arr)

[1 2 3]


## Data Type Conversion

In [53]:
# float to int

arr = np.array([1.1,2.2,3.3,4.4])
print('old array :',arr)
print('old array data type :', arr.dtype)
print('*'*100)
new_arr = arr.astype('i')
print('new array',new_arr)
print('new array data type :',new_arr.dtype)


old array : [1.1 2.2 3.3 4.4]
old array data type : float64
****************************************************************************************************
new array [1 2 3 4]
new array data type : int32


In [54]:
# int to bool 
arr = np.array([1,2,3,4,0])
print('old array:',arr)
print('old array data type:',arr.dtype)
print('*'*100)
new_arr = arr.astype (bool)
print('new array',new_arr)
print('new array data type:',new_arr.dtype)

old array: [1 2 3 4 0]
old array data type: int32
****************************************************************************************************
new array [ True  True  True  True False]
new array data type: bool


## Differance between copy and view

## Copy :
#### A copy is a new array that has the same data as the original array.changes made to the copy do not affect the original array, and vice versa


## View :
#### A view is a new array that refers to the same data as the orinal array. changes made to the view affect the original array , and vice versa


In [55]:
a = np.array([1,2,3,4,5])
print('original array:',a)
b=a.copy()
print('copid array:',b)
print('now we will update the original array "1 to 100"')
a[0]=100
print('original array after update :',a)
print('copied array after update in original:',b)

original array: [1 2 3 4 5]
copid array: [1 2 3 4 5]
now we will update the original array "1 to 100"
original array after update : [100   2   3   4   5]
copied array after update in original: [1 2 3 4 5]


In [56]:
a=np.array([1,2,3,4,5])
print('original array:',a)
b=a .view()
print('copied array :',a)
print('now we will update the original array "1 to 100"')
a[0]=100

print('original array after update :',a)
print('copied array after update in original :',b)


original array: [1 2 3 4 5]
copied array : [1 2 3 4 5]
now we will update the original array "1 to 100"
original array after update : [100   2   3   4   5]
copied array after update in original : [100   2   3   4   5]


In [57]:
# copy : it is going to creat new instance fpr ypur value

arr = np .array([1,2,3,4,5])
x = arr.copy()# separat object required 
arr[0]= 42 # updated arr 0 th index

print (arr )
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [58]:
arr = np.array ([1,2,3,4,5,6])
x = arr.copy()# separat object required
print(x)
x[0] = 100
print(x)

print(arr)
#print(x)

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [59]:
# view 

arr = np.array([1,2,3,4,5])
x = arr.view ()

#x = arr 
x[0] = 200
print(x)
print(x)

[200   2   3   4   5]
[200   2   3   4   5]


In [60]:
a = np.array ([1,2,3])
b = a.view()
b[0]=4


print(a)# output : [4,2,3]
print(b)# output: [4,2,3]

[4 2 3]
[4 2 3]


### Base concept : how to identify copy or  view

#### That will possible  by using "base" fuction
if you are referring to identifying whether a numpy array is a copy or a view (a differant view of the same data) , you can use the base attribute of the array.the base attribute returns none for arrays that own their data and it returns the base object forrrrrrr arrays that are views

In [61]:
arr = np .array([1,2,3,4,5])

x = arr.copy()
y = arr .view()

print(x.base )
print(y.base)

None
[1 2 3 4 5]


## Numpy Array Reshaping 

In [62]:
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.shape)
print(arr.shape)
print('\n')
newarr=arr.reshape(12,1)
print(newarr)
                

(12,)
(12,)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [63]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [64]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.size)
print(arr.shape)
print('\n')
newarr=arr.reshape(3,2,2)
print(newarr)

12
(12,)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [65]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [66]:
# creat a 2D array and then covert it into 1D array

arr = np.array([[11,44,77,88,99,55]])
newarr=arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[11 44 77 88 99 55]]
2
****************************************************************************************************
[11 44 77 88 99 55]
1


In [67]:
arr = np.array([[11,44,77],[88,99,55]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[11 44 77]
 [88 99 55]]
2
****************************************************************************************************
[11 44 77 88 99 55]
1


In [68]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape(3,2)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[11 44 77 88 99 55]
1
****************************************************************************************************
[[11 44]
 [77 88]
 [99 55]]
2


In [69]:
# cvert 3D array into 1D array
arr = np.array([[[11,44,77,88,99,55]],[[111,441,717,188,919,515]]])
newarr = arr.reshape(12,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[[ 11  44  77  88  99  55]]

 [[111 441 717 188 919 515]]]
3
****************************************************************************************************
[ 11  44  77  88  99  55 111 441 717 188 919 515]
1


In [70]:
arr = np.array([11,44,77,88,99,55,111,441,717,188,919,515])
newarr = arr.reshape(1,3,4)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[ 11  44  77  88  99  55 111 441 717 188 919 515]
1
****************************************************************************************************
[[[ 11  44  77  88]
  [ 99  55 111 441]
  [717 188 919 515]]]
3


In [71]:
import numpy as np


In [72]:
# convert 4D array into 1D array 
arr = np.array ([[[[11,44,77,88,99,55]]]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)


[[[[11 44 77 88 99 55]]]]
4
****************************************************************************************************
[11 44 77 88 99 55]
1


In [73]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape((3,2))
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[11 44 77 88 99 55]
1
****************************************************************************************************
[[11 44]
 [77 88]
 [99 55]]
2


## Numpy Array Reshape Flatten Unknown Dimention

#### if user dont know any one dimention out 3 dimention then numpy can obtain it for user have mention the _1 for thaat dim

In [74]:
# unkown Dimention 
arr = np.array ([1,2,3,4,5,6,7,8,9])

newarr = arr.reshape(3,3,-1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


#### if u want to a 1-D  Araay using N-D array 

In [75]:
# flattenting (reshshape/covrt in scalar vector) an array

arr = np.array([[10,20,30],[40,50,60]])

print(arr)
print(arr.shape)

newarr=arr.reshape(-1)
print(newarr)

[[10 20 30]
 [40 50 60]]
(2, 3)
[10 20 30 40 50 60]


## Numpy Array Iterating

### iterating means that you going each element of the array

In [80]:
# iterating on 2-D array 
arr = np.array ([[11,22,33],[10,20,30]])

# print(arr)

for x in arr: # x is taking elements here
    print(x)

[11 22 33]
[10 20 30]


In [82]:
# interating on scalarelement of 2-D array

arr = np.array([[1,2,3],[4,5,6]])
for x in arr : # here x is hplding list of element
    for i in x:
        print(i)
    

1
2
3
4
5
6


In [85]:
#iterating on scalar elememntof 3-D array

arr = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr : 
#    print(x,'\n')
    for i in x:
        for j in i :
            print(j,'\n')

1 

2 

3 

4 

5 

6 

7 

8 

9 

10 

11 

12 



### using nditer()

In [86]:
# iterating on 3-D array 
 arr =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
    
y = np .nditer(arr)

 for x in y:
        print(x)

IndentationError: unexpected indent (621175081.py, line 2)